########################
## Default properties ##
########################
# SPRING FRAMEWORK
sphere:
  web-security:
    permit-all:
    - "/actuator/**"
    - ${rest.api-prefix.internal}**
    - ${rest.api-prefix.integration}**